In [3]:
from sklearn.metrics import confusion_matrix

In [12]:
import ou_model as om
import numpy as np

## Stuttering Test

In [21]:
X_test_normal = np.load('X_test_normal.npy')
X_test_glitch = np.load('X_test_stuttering.npy')
X_test = np.concatenate((X_test_normal[122:222], X_test_glitch[50:150]))
y_test = np.ones(200)
y_test[0:100] = 0
y_pred = om.test_stuttering(X_test)
print((y_pred == y_test).sum())
confusion_matrix(y_test, y_pred)

Transform Time for stuttering:  8.664623022079468
Remaining Time for stuttering:  0.22960400581359863
185


array([[95,  5],
       [10, 90]])

## Triangulation Test

In [16]:
X_test_normal = np.load('X_test_normal.npy')
X_test_glitch = np.load('X_test_triangulation.npy')
X_test = np.concatenate((X_test_normal[255:355], X_test_glitch[0:100]))
y_test = np.ones(200)
y_test[0:100] = 0
y_pred = om.test_triangulation(X_test)
print((y_pred == y_test).sum())
confusion_matrix(y_test, y_pred)

/Users/tou2/Downloads/Project/yy-ModelEnsemble/ou_model.py:27: RuntimeWarning: divide by zero encountered in log
  magnitude_spectrum = 20*np.log(np.abs(fshift))


Transform Time for triangulation:  9.187949895858765
Remaining Time for triangulation:  0.3305940628051758
200


array([[100,   0],
       [  0, 100]])

## Square Patch Test

In [32]:
X_test_normal = np.load('X_test_normal.npy')
X_test_glitch = np.load('X_test_square_patch.npy')
X_test = np.concatenate((X_test_normal[120:220], X_test_glitch[0:100]))
y_test = np.ones(200)
y_test[0:100] = 0
y_pred = om.test_square_patch(X_test)
print((y_pred == y_test).sum())
confusion_matrix(y_test, y_pred)

Transform Time for square patch:  10.2184739112854
Remaining Time for square patch:  0.2304079532623291
126


array([[58, 42],
       [32, 68]])

## Shape Test

In [9]:
X_test_normal = np.load('X_test_normal.npy')
X_test_glitch = np.load('X_test_shape.npy')
X_test = np.concatenate((X_test_normal[0:100], X_test_glitch[0:100]))
y_test = np.ones(200)
y_test[0:100] = 0
y_pred = om.test_shape(X_test)
print((y_pred == y_test).sum())
confusion_matrix(y_test, y_pred)

Transform Time for shapes:  9.691434144973755
Remaining Time for shapes:  0.29584598541259766
162


array([[80, 20],
       [18, 82]])